### PR TITLE
fix(installation): use new installation URLs

### LINKED ISSUE #2449: Use GitHub releases for installation
## Summary
This PR updates the Forge installation process to use GitHub releases instead of custom domains.

## Changes
- Updated install script links from `forgecode.dev` to GitHub raw content
- Updated binary downloads from custom service to GitHub releases API
- Updated auto-update command to use GitHub raw link

## Benefits
- More transparent installation process
- Removes dependency on custom domain
- Uses GitHub's reliable releases infrastructure

Co-Authored-By: ForgeCode <noreply@forgecode.dev>

### PR DESCRIPTION
**Pull request by ravshansbox**
## Summary
This PR updates the Forge installation process to use GitHub releases instead of custom domains.

## Changes
- Updated install script links from `forgecode.dev` to GitHub raw content
- Updated binary downloads from custom service to GitHub releases API
- Updated auto-update command to use GitHub raw link

## Benefits
- More transparent installation process
- Removes dependency on custom domain
- Uses GitHub's reliable releases infrastructure

## Files Changed
- `README.md` - Updated installation commands
- `install.sh` - Updated download URLs
- `crates/forge_main/src/update.rs` - Updated auto-update command

Closes #2449

Co-Authored-By: ForgeCode <noreply@forgecode.dev>

### CODE REVIEW

File: crates/forge_main/src/update.rs [hunk 1]
```diff
@@ -9,7 +9,7 @@ use update_informer::{Check, Version, registry};
 async fn execute_update_command(api: Arc<impl API>) {
     // Spawn a new task that won't block the main application
     let output = api
-        .execute_shell_command_raw("curl -fsSL https://forgecode.dev/install.sh | sh")
+        .execute_shell_command_raw("curl -fsSL https://raw.githubusercontent.com/antinomyhq/forge/main/install.sh | sh")
```
Comment (tusharmath) [inline crates/forge_main/src/update.rs]:
```suggestion
        .execute_shell_command_raw("curl -fsSL https://forgecode.dev/cli | sh")
```

Comment (tusharmath) [reply crates/forge_main/src/update.rs]: We need to delete the `install.sh` from the current repo. Refer to the install script here - `https://forgecode.dev/`

File: install.sh [hunk 2]
```diff
@@ -206,7 +206,11 @@ echo -e "${BLUE}Detected platform: $TARGET${NC}"
 VERSION="${1:-latest}"
 
 # Construct download URL
-DOWNLOAD_URL="https://release-download.tailcall.workers.dev/download/$VERSION/forge-$TARGET"
+if [ "$VERSION" = "latest" ]; then
+    DOWNLOAD_URL="https://github.com/antinomyhq/forge/releases/latest/download/forge-$TARGET"
+else
+    DOWNLOAD_URL="https://github.com/antinomyhq/forge/releases/download/$VERSION/forge-$TARGET"
```
Comment (tusharmath) [inline install.sh]: we should delete this file.

File: README.md [hunk 3]
```diff
@@ -1,7 +1,7 @@
 <h1 align="center">⚒️ Forge: AI-Enhanced Terminal Development Environment</h1>
 <p align="center">A comprehensive coding agent that integrates AI capabilities with your development environment</p>
 
-<p align="center"><code>curl -fsSL https://forgecode.dev/install.sh | sh</code></p>
+<p align="center"><code>curl -fsSL https://raw.githubusercontent.com/antinomyhq/forge/main/install.sh | sh</code></p>
```
Comment (tusharmath) [inline README.md]:
```suggestion
<p align="center"><code>curl -fsSL https://forgecode.dev/ | sh</code></p>
```

File: README.md [hunk 4]
```diff
@@ -41,7 +41,7 @@
 To get started with Forge, run the command below:
 
 ```bash
-curl -fsSL https://forgecode.dev/install.sh | sh
+curl -fsSL https://raw.githubusercontent.com/antinomyhq/forge/main/install.sh | sh
```
Comment (tusharmath) [inline README.md]:
```suggestion
curl -fsSL https://forgecode.dev/ | sh
```

File: crates/forge_main/src/update.rs (hunk 1 above)
Comment (ravshansbox) [reply crates/forge_main/src/update.rs]: [https://forgecode.dev/install.sh](https://forgecode.dev/install.sh) is returning 404

File: README.md (hunk 4 above)
Comment (ravshansbox) [reply README.md]: or maybe [https://forgecode.dev/cli](https://forgecode.dev/cli)?
