### PR TITLE
fix: zero usage

### LINKED ISSUE #750: bug: zero usage information
Sometimes, even after performing a long run the usage on the console still shows `0`. We also have an `estimate_token_count` which can be leveraged to get an approx token usage.

**Objective**
- Identify the issue and produce a fix.
- Produce the smallest diff to fix this issue

### PR DESCRIPTION
**Pull request by laststylebender14**
/claim #750
/fixes #750

### CODE REVIEW

File: crates/forge_domain/src/orch.rs [hunk 1]
```diff
@@ -193,6 +193,26 @@ impl<A: Services> Orchestrator<A> {
...
+                // If provider doesn't provide usage, we can estimate it.
+                let mut usage = Usage::default();
+                usage.estimated_tokens = Some(context.estimate_token_count());
+                if request_usage.is_none() {
+                    request_usage = Some(usage.clone());
+                }
+                debug!(usage = ?usage, "Usage");
+                self.send(agent, ChatResponse::Usage(usage)).await?;
+            }
+
```
Comment (tusharmath) [inline crates/forge_domain/src/orch.rs:218]: Can we simplify this code? use some functions to handle this more cleanly.
