### PR TITLE
fix: use relative path for autocomplete fuzzy match

### LINKED ISSUE #1295: feat: make `@` autocomplete perform a fuzzy search on full path
Current implementation performs a search on just the file name, doing on the relative path can be more useful specially when files with similar names exist in the dir.

### PR DESCRIPTION
**Pull request by jayantpranjal0**
Closes #1295

### CODE REVIEW

**Comment by tusharmath** [comment]
For the following:
```
@foo bar baz[TAB]
```
The search key should be `foo bar baz`. 

Currently only text up until the first whitespace is used as the needle.

File: crates/forge_main/src/completer/input_completer.rs [hunk 1]
```diff
@@ -86,6 +84,18 @@ impl Completer for InputCompleter {
...
+    let mut term_string = term.to_string();
+    if term_string.ends_with('$') {
+        term_string.insert(term_string.len() - 1, '\\');
+    }
+    if term_string.starts_with('\'') || term_string.starts_with('^') || term_string.starts_with('!')
+    {
+        term_string = format!("\\{term_string}");
+    }
+    term_string
+}
```
Comment (tusharmath) [inline crates/forge_main/src/completer/input_completer.rs]: Tried running the current tests without this function, and they all pass. Not sure why we need this still.

Comment (jayantpranjal0) [reply crates/forge_main/src/completer/input_completer.rs]: added a pr with new tests #1310
