### PR TITLE
fix: Implement retry mechanism with exponential backoff for agent 

### LINKED ISSUE #461: Tool Call Parsing Error: Failed to parse tool_forge_event_dispatch arguments
### Issue
I'm randomly encountering errors when making tool calls. The system reports:

```
Failed to parse tool call: [ToolCallPart { call_id: Some(ToolCallId("toolu_017seav7Ng1vXMKrXdqmRh8b")), name: Some(ToolName("tool_forge_event_dispatch")), arguments_part: "" }, ToolCallPart { call_id: None, name: None, arguments_part: "" }, ToolCallPart { call_id: None, name: None, arguments_part: "{"id": "" }, ToolCallPart { call_id: None, name: None, arguments_part: "time_ret" }, ToolCallPart { call_id: None, name: None, arguments_part: "rieval" }, ToolCallPart { call_id: None, name: None, arguments_part: """ }]
Caused by: Invalid tool call arguments: EOF while parsing an object at line 1 column 23 [tokens 4502/87/4589]
```

### Observed Behavior
- The error occurs randomly
- The tool call argument JSON appears to be malformed
- The string "time_retrieval" seems to be split across multiple argument parts
- Happening for the Title agent.

### PR DESCRIPTION
**Pull request by amitksingh1490**
fixes #461

### CODE REVIEW

File: crates/forge_domain/src/orch.rs [hunk 1]
```diff
@@ -41,6 +90,9 @@ impl<A: App> Orchestrator<A> {
             app,
             sender,
             conversation: Arc::new(RwLock::new(conversation)),
+            retry_strategy: ExponentialBackoff::from_millis(200)
+                .factor(2)
+                .take(MAX_RETRY_ATTEMPTS),
```
Comment (tusharmath) [inline crates/forge_domain/src/orch.rs]: Make this configurable via forge.yaml.

**Comment by amitksingh1490** [comment]
send a chat response event on retry and handle in ui to show it on the console

File: crates/forge_domain/src/orch.rs [hunk 2]
```diff
@@ -6,12 +6,60 @@ use async_recursion::async_recursion;
...
+        )
+    } else {
+        false
+    };
+
+    if !is_retriable {
+        tracing::error!(
+            operation = %operation_name,
+            error = ?err,
+            "Operation failed with non-retryable error"
```
Comment (amitksingh1490) [inline crates/forge_domain/src/orch.rs]: we can remove this and handle it on ui

File: crates/forge_domain/src/error.rs [hunk 3]
```diff
@@ -43,6 +43,58 @@ pub enum Error {
...
+/// Kinds of errors that can be retried
+#[derive(Debug, Clone, serde::Serialize)]
+pub enum RetryErrorKind {
+    /// Missing tool name
+    ToolCallMissingName,
+    /// Invalid tool call arguments
+    ToolCallArgument,
+    /// Invalid tool call XML
+    ToolCallParse,
+}
```
Comment (tusharmath) [inline crates/forge_domain/src/error.rs]: Don't need this. Lets just use StdErr.

File: crates/forge_domain/src/error.rs [hunk 4]
```diff
@@ -43,6 +43,58 @@ pub enum Error {
...
+    pub fn is_retriable(err: &anyhow::Error) -> bool {
+        if let Some(domain_err) = err.downcast_ref::<Error>() {
+            matches!(
+                domain_err,
+                Error::ToolCallParse(_) | Error::ToolCallArgument(_) | Error::ToolCallMissingName
+            )
+        } else {
+            false
+        }
+    }
```
Comment (tusharmath) [inline crates/forge_domain/src/error.rs]: Method should not be in error.rs.

File: crates/forge_domain/src/chat_response.rs [hunk 5]
```diff
@@ -12,4 +12,13 @@ pub enum ChatResponse {
     ToolCallEnd(ToolResult),
     Usage(Usage),
     Event(Event),
+    /// Represents a retry attempt due to a retriable error
+    Retry {
+        /// The error that caused the retry
+        error: RetryError,
```
Comment (tusharmath) [inline crates/forge_domain/src/chat_response.rs:18]:
```suggestion
        error: String,
```

Comment (tusharmath) [inline crates/forge_domain/src/chat_response.rs]:
```suggestion
        reason: String,
```

use `reason` to specify "why" are we retrying.

File: crates/forge_domain/src/orch.rs [hunk 6]
```diff
@@ -14,6 +16,34 @@ use crate::*;
...
+                message: ChatResponse::Retry {
+                    error: RetryError::from_error(err),
+                    attempt,
+                    max_attempts,
+                },
+            }))
+            .await;
+    }
+    is_retriable
+}
```
Comment (tusharmath) [inline crates/forge_domain/src/orch.rs]: Create a new struct that holds all the retry related information. Use simpler method calls so that easier work with.
