### PR TITLE
fix: Update message sending logic to include Custom type responses

### LINKED ISSUE #558: bug: Sometimes the title dispatched doesn't show up on the console
Image

[2025-03-20_08-57-32-dump.json](https://github.com/user-attachments/files/19358513/2025-03-20_08-57-32-dump.json)

### PR DESCRIPTION
**Pull request by amitksingh1490**
fixes #558

### CODE REVIEW

File: crates/forge_domain/src/orch.rs [hunk 1]
```diff
@@ -57,8 +57,10 @@ impl<A: App> Orchestrator<A> {
 
     async fn send_message(&self, agent: &Agent, message: ChatResponse) -> anyhow::Result<()> {
         if let Some(sender) = &self.sender {
-            // Only send message if hide_content is false
-            if !agent.hide_content.unwrap_or_default() {
+            // Send message if it's a Custom type or if hide_content is false
+            if matches!(&message, ChatResponse::Custom(_))
```
Comment (tusharmath) [inline crates/forge_domain/src/orch.rs]: Lets rename:
```suggestion
            if matches!(&message, ChatResponse::Event(_))
```

File: crates/forge_domain/src/orch.rs [hunk 2]
```diff
@@ -57,8 +57,10 @@ impl<A: App> Orchestrator<A> {
 
     async fn send_message(&self, agent: &Agent, message: ChatResponse) -> anyhow::Result<()> {
```
Comment (tusharmath) [inline crates/forge_domain/src/orch.rs]: There is `send` and `send_message` can you merge them in to `send`

Comment (amitksingh1490) [reply crates/forge_domain/src/orch.rs]: ok
