### PR TITLE
fix: Add OS-specific multiline shortcuts in /help command

### LINKED ISSUE #1879: feat(ui): update `/info` command to display correct multiline input shortcut per OS
#### Description  
Currently, regardless of the operating system (Windows, Linux, macOS) on which Forge is running, invoking the `/info` command always displays the multiline input shortcut as `<OPT+ENTER>`. This is misleading for Windows and Linux users, for whom the correct shortcut is `<ALT+ENTER>`.

#### Current Behavior  
The `/info` command on all platforms shows:  
`<OPT+ENTER>: Insert new line (multiline input)`  
when on Windows and Linux, it should indicate `<ALT+ENTER>` instead of `<OPT+ENTER>`.

#### Proposed Changes  
Update the `/info` command output to dynamically display the correct multiline input shortcut based on the operating system Forge is running on:  
- macOS: `<OPT+ENTER>`  
- Windows/Linux: `<ALT+ENTER>`

#### Benefits  
- Improves user experience by showing accurate shortcut information tailored to the user's OS, reducing confusion.  
- Enhances cross-platform usability and professionalism of the Forge CLI interface.

#### Implementation Notes  
Implement OS detection in the CLI command `/info` and conditionally render the shortcut string accordingly.

### PR DESCRIPTION
**Pull request by dariuszkowalski-com**
## Summary

Implements dynamic keyboard shortcuts for multiline input based on operating system, resolving issue #1879. The `/info` command now displays platform-appropriate shortcuts instead of showing macOS shortcuts on all platforms.

### Core Implementation
- **Added `get_multiline_shortcut()` function** in `crates/forge_main/src/info.rs` that detects OS and returns appropriate shortcuts
- **Updated `Info::from()` implementation** to accept optional `Environment` parameter for OS detection
- **Modified UI layer** in `crates/forge_main/src/ui.rs` to pass environment information to Info display

### Platform Support
- **macOS**: `<OPT+ENTER>`
- **Windows/Linux**: `<ALT+ENTER>`
- **Fallback**: `<ALT+ENTER>` for unknown systems

### Testing
- Added comprehensive unit tests covering all major operating systems
- Included integration tests for environment-aware Info creation
- Maintained backward compatibility tests
- All 1226 existing tests continue to pass

### Backward Compatibility
- Original `Info::from(&ForgeCommandManager)` implementation preserved
- Optional Environment parameter allows seamless integration with existing code
- Graceful fallback to `<ALT+ENTER>` when environment info unavailable

## Verification

- ✅ Code compiles without warnings
- ✅ All tests pass (1226 tests)
- ✅ Code formatting follows Rust standards
- ✅ No snapshot issues detected
- ✅ OS-specific shortcuts display correctly on each platform

## Technical Details

The implementation uses runtime OS detection via `env.os` from forge_api Environment struct. The solution follows Rust idioms with tuple-based `From` trait implementation and maintains clean separation of concerns.

Fixes #1879

### CODE REVIEW

File: crates/forge_main/src/info.rs [hunk 1]
```diff
@@ -391,24 +391,48 @@ fn get_git_branch() -> Option<String> {
...
+        (command_manager, env): (&ForgeCommandManager, Option<&forge_api::Environment>),
+    ) -> Self {
         let mut info = Info::new().add_title("COMMANDS");
 
         for command in command_manager.list() {
             info = info.add_key_value(command.name, command.description);
         }
 
+        // Determine multiline shortcut based on OS
+        let multiline_shortcut = env
```
Comment (amitksingh1490) [inline crates/forge_main/src/info.rs]: we can do this check at compile time as we have different binaries for different os

```rust
#[cfg(target_os = "macos")]
let multiline_shortcut = "<OPT+ENTER>";

#[cfg(not(target_os = "macos"))]
let multiline_shortcut = "<ALT+ENTER>";
```
this way we can use existing code as is
