### PR TITLE
fix: compaction for codex spark model

### LINKED ISSUE #2963: [Bug]: gpt-5.3-codex-spark has 128k max context not 272k
### Bug Description

Using **gpt-5.3-codex-spark** with forge leads to out of context errors due to incorrect max context configuration.

Spark is a model hosted on cerebras hardware (the wafer scale inference chips), which have limited on-die VRAM. OpenAI specifies 128k context size for the model here: https://openai.com/index/introducing-gpt-5-3-codex-spark/

Image

Currently Forge reports 272k context for this model, so if it is used Forge eventually exceeds the model's context limit.

### Steps to Reproduce

Use the model and work on a project.

### Expected Behavior

Should not run out of context.

### Actual Behavior

Runs out of context.

### Forge Version

2.9.8

### Operating System & Version

_No response_

### AI Provider

OpenAI

### Model

gpt-5.3-codex-spark

### Installation Method

Other

### Configuration

```yaml

```

### PR DESCRIPTION
**Pull request by amitksingh1490**
fixes #2963

### CODE REVIEW

File: crates/forge_domain/src/agent.rs [hunk 1]
```diff
@@ -231,6 +231,46 @@ impl Agent {
...
+    /// context window. If a threshold is configured but exceeds 70% of the
+    /// context window, caps it to 70% to ensure sufficient headroom for tool
+    /// outputs and prevent context_length_exceeded errors.
+    ///
+    /// # Arguments
+    /// * `selected_model` - The model that will be used for this agent
+    ///
+    /// # Returns
+    /// The agent with a safe token_threshold configured
+    pub fn compaction_threshold(mut self, selected_model: Option<&Model>) -> Self {
```
Comment (tusharmath) [inline crates/forge_domain/src/agent.rs:250]: Can we create two separate configurations - one which is hardcoded by token count and one which is a percentage of the context window, we will take min of the two settings.
