### PR TITLE
fix: avoid unwrapping when receiver is dropped.

### LINKED ISSUE #569: bug: forge panics when receiver is dropped.
Image

### PR DESCRIPTION
**Pull request by laststylebender14**
fixes #569

### CODE REVIEW

File: crates/forge_api/src/executor.rs [hunk 1]
```diff
@@ -25,16 +25,15 @@ impl<F: App> ForgeExecutorService<F> {
...
         Ok(MpscStream::spawn(move |tx| async move {
             let tx = Arc::new(tx);
 
             let orch = Orchestrator::new(app, conversation, Some(tx.clone()));
 
-            match orch.dispatch(request.event).await {
-                Ok(_) => {}
-                Err(err) => tx.send(Err(err)).await.unwrap(),
+            if let Err(err) = orch.dispatch(request.event).await {
+                let _ = tx.send(Err(err)).await;
```
Comment (tusharmath) [inline crates/forge_api/src/executor.rs]: How can tx not be dropped?

Comment (laststylebender14) [reply crates/forge_api/src/executor.rs]: discussed

File: crates/forge_api/src/executor.rs [hunk 2]
```diff
@@ -25,16 +26,18 @@ impl<F: App> ForgeExecutorService<F> {
...
         Ok(MpscStream::spawn(move |tx| async move {
             let tx = Arc::new(tx);
 
             let orch = Orchestrator::new(app, conversation, Some(tx.clone()));
 
-            match orch.dispatch(request.event).await {
-                Ok(_) => {}
-                Err(err) => tx.send(Err(err)).await.unwrap(),
+            if let Err(err) = orch.dispatch(request.event).await {
+                error!("Error occured in orchestrator: {:#?}", err);
```
Comment (tusharmath) [inline crates/forge_api/src/executor.rs]:
```suggestion
```

This isn't needed.
